import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:google_fonts/google_fonts.dart';

import 'core/di/injection.dart';
import 'core/router/app_router.dart';
import 'core/services/messaging_service.dart';
import 'core/theme/app_theme.dart';
import 'core/constants/app_constants.dart';
// import 'firebase_options.dart'; // <-- generated by flutterfire configure

final scaffoldMessengerKey = GlobalKey<ScaffoldMessengerState>();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GoogleFonts.config.allowRuntimeFetching = false;
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);

  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  await setupDependencies();

  runApp(const StockShaalaApp());

  // Requests notification permission (shows a system dialog) — must happen
  // after the first frame is drawn, otherwise the app appears frozen since
  // the dialog can't render until runApp() has handed off to the engine.
  sl<MessagingService>().init(
    onForegroundMessage: (message) {
      final notification = message.notification;
      if (notification == null) return;
      scaffoldMessengerKey.currentState?.showSnackBar(
        SnackBar(
          content: Text(notification.title ?? notification.body ?? ''),
        ),
      );
    },
    onMessageOpenedApp: (message) {
      debugPrint('Notification opened app: ${message.messageId}');
    },
  );
}

class StockShaalaApp extends StatelessWidget {
  const StockShaalaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      scaffoldMessengerKey: scaffoldMessengerKey,
      theme: AppTheme.dark,
      routerConfig: AppRouter.router,
    );
  }
}
